### ISSUE TITLE
BaseException 'key not in tree' after blockchain reorg 436015

### ISSUE THREAD

**Issue by santzi** [santzi/electrum-dash-server#1]
After pruning from scratch:

[14/03/2016-16:28:09] block 436013 (8 0.18s) a4445df699a5e709f7803b6319ebd8a956c1f1a2090f0670c0b6bcb8d19f6d0e (46.25tx/s, 0.09s/block)
[14/03/2016-16:29:09] block 436014 (1 0.01s) 13bce6c609d9dfdcf806724d28d56ccd21db989628c202f1ab07c233f1f738fa (46.32tx/s, 0.09s/block)
[14/03/2016-16:29:59] block 436015 (3 0.04s) 7e20a4021b87f44133b50a62489e60b6f653c17fd46ba733c2b1fd50fc3d79c6 (46.48tx/s, 0.09s/block)
[14/03/2016-16:30:59] blockchain reorg 436015 00000000000969bd8aa7852d5c41de0b990a1cf0ad67ad2ec2863e53574dc8c6 00000000000f2b099122490ba20421348479f629cad38565efc6163
351e90655
[14/03/2016-16:30:59] block 436014 (3 0.02s) 13bce6c609d9dfdcf806724d28d56ccd21db989628c202f1ab07c233f1f738fa (46.71tx/s, 0.09s/block)
[14/03/2016-16:44:33] recv error: error(9, 'Bad file descriptor')
[14/03/2016-16:44:47] SSL    108.44.238.26:49417    1 all_seeing_eye
[14/03/2016-16:45:15] SSL    108.44.238.26:49523    1 all_seeing_eye
[14/03/2016-16:45:28] SSL    108.44.238.26:49581    1 all_seeing_eye
[14/03/2016-16:45:42] SSL    108.44.238.26:49636    1 all_seeing_eye
[14/03/2016-16:45:54] SSL    108.44.238.26:49715    1 all_seeing_eye
[14/03/2016-16:46:07] SSL    108.44.238.26:49769    1 all_seeing_eye
[14/03/2016-16:46:19] SSL    108.44.238.26:49821    1 all_seeing_eye
[14/03/2016-16:46:31] SSL    108.44.238.26:49863    1 all_seeing_eye
[14/03/2016-16:46:44] SSL    108.44.238.26:49912    1 all_seeing_eye
[14/03/2016-16:46:56] SSL    108.44.238.26:49962    1 all_seeing_eye
[14/03/2016-16:47:09] SSL    108.44.238.26:50021    1 all_seeing_eye
[14/03/2016-16:47:24] SSL    108.44.238.26:50075    1 all_seeing_eye
[14/03/2016-16:47:36] SSL    108.44.238.26:50117    1 all_seeing_eye
[14/03/2016-16:47:48] SSL    108.44.238.26:50165    1 all_seeing_eye

Occurs every time on start after this.

INFO:electrum-dash:Starting Electrum Dash server on 192.168.1.33
INFO:electrum-dash:Database version 3.
INFO:electrum-dash:Pruning limit for spent outputs is 100.
INFO:electrum-dash:Blockchain height 436015
INFO:electrum-dash:UTXO tree root hash: 13bce6c609d9dfdcf806724d28d56ccd21db989628c202f1ab07c233f1f738fa
INFO:electrum-dash:Coins in database: 629435663379199
INFO:electrum-dash:TCP server started on 192.168.1.33:50007
INFO:electrum-dash:SSL server started on 192.168.1.33:50008
INFO:electrum-dash:blockchain reorg 436015 00000000000969bd8aa7852d5c41de0b990a1cf0ad67ad2ec2863e53574dc8c6 00000000000f2b099122490ba20421348479f629cad38565efc6163351e90655
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/home/jeppa/Downloads/git/oma_electrum-dash-server/electrum-dash-server/src/blockchain_processor.py", line 104, in do_catch_up
    self.catch_up(sync=False)
  File "/home/jeppa/Downloads/git/oma_electrum-dash-server/electrum-dash-server/src/blockchain_processor.py", line 703, in catch_up
    n = self.import_block(block, self.storage.last_hash, self.storage.height, revert=True)
  File "/home/jeppa/Downloads/git/oma_electrum-dash-server/electrum-dash-server/src/blockchain_processor.py", line 442, in import_block
    self.storage.revert_transaction(txid, tx, block_height, touched_addr, undo)
  File "/home/jeppa/Downloads/git/oma_electrum-dash-server/electrum-dash-server/src/storage.py", line 671, in revert_transaction
    self.revert_add_to_history(addr, txid, x.get('index'), x.get('value'), block_height)
  File "/home/jeppa/Downloads/git/oma_electrum-dash-server/electrum-dash-server/src/storage.py", line 587, in revert_add_to_history
    self.delete_key(key + txo)
  File "/home/jeppa/Downloads/git/oma_electrum-dash-server/electrum-dash-server/src/storage.py", line 507, in delete_key
    path = self.get_path(leaf)
  File "/home/jeppa/Downloads/git/oma_electrum-dash-server/electrum-dash-server/src/storage.py", line 478, in get_path
    raise BaseException('key not in tree', target.encode('hex'))
BaseException: ('key not in tree', 'eb35facb9908f6004b546c4742a4baa832a95cc0d31d910e7223d59ba9da15f909c69f1824883d6f1ac5faa06e122619007333bd01000000')

**Comment by santzi** [comment]
I will close this issue. No valid anymore.
